// <auto-generated />
using System;
using Climedio.Repositorio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Climedio.Repositorio.Migrations
{
    [DbContext(typeof(ClimedioContexto))]
    [Migration("20250128204033_primeiro")]
    partial class primeiro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Climedio.Dominio.Entidades.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("AgendamentoId");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Ativo");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT")
                        .HasColumnName("DataHora");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("Observacao");

                    b.Property<int>("UsuarioIdPaciente")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UsuarioIdPaciente");

                    b.Property<int>("UsuarioIdProfissional")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UsuarioIdProfissional");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioIdPaciente");

                    b.HasIndex("UsuarioIdProfissional");

                    b.ToTable("Agendamentos", (string)null);
                });

            modelBuilder.Entity("Climedio.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("UsuarioID");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Ativo");

                    b.Property<string>("Cpf")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("DataNascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(130)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome");

                    b.Property<string>("NomeSocial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Senha");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Climedio.Dominio.Entidades.Agendamento", b =>
                {
                    b.HasOne("Climedio.Dominio.Entidades.Usuario", "UsuarioPaciente")
                        .WithMany("AgendamentosPaciente")
                        .HasForeignKey("UsuarioIdPaciente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Climedio.Dominio.Entidades.Usuario", "UsuarioProfissional")
                        .WithMany("AgendamentosProfissional")
                        .HasForeignKey("UsuarioIdProfissional")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UsuarioPaciente");

                    b.Navigation("UsuarioProfissional");
                });

            modelBuilder.Entity("Climedio.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("AgendamentosPaciente");

                    b.Navigation("AgendamentosProfissional");
                });
#pragma warning restore 612, 618
        }
    }
}
